import React from 'react';
import ReactDOM from 'react-dom/client';
import './styles/index.scss';
import SmoothScroll from './components/SmoothScroll';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <>
    <SmoothScroll />
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
    <h1>ciao</h1>
  </>
);
